/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Category model module.
 * @module model/Category
 * @version 1.5
 */
export class Category {
  /**
   * Constructs a new <code>Category</code>.
   * A table of catergories used in multiple types of records
   * @alias module:model/Category
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Category} obj Optional instance to populate.
   * @return {module:model/Category} The populated <code>Category</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Category();
      if (data.hasOwnProperty('catid'))
        obj.catid = ApiClient.convertToType(data['catid'], 'Number');
      if (data.hasOwnProperty('catergoryName'))
        obj.catergoryName = ApiClient.convertToType(data['catergoryName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} catid
 */
Category.prototype.catid = undefined;

/**
 * @member {String} catergoryName
 */
Category.prototype.catergoryName = undefined;

/**
 * @member {String} description
 */
Category.prototype.description = undefined;

