/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ComponentsparametersvendorID} from './ComponentsparametersvendorID';
import {InvoiceItems} from './InvoiceItems';

/**
 * The Invoice model module.
 * @module model/Invoice
 * @version 1.5
 */
export class Invoice {
  /**
   * Constructs a new <code>Invoice</code>.
   * @alias module:model/Invoice
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Invoice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Invoice} obj Optional instance to populate.
   * @return {module:model/Invoice} The populated <code>Invoice</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Invoice();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('vendorID'))
        obj.vendorID = ComponentsparametersvendorID.constructFromObject(data['vendorID']);
      if (data.hasOwnProperty('recieveDate'))
        obj.recieveDate = ApiClient.convertToType(data['recieveDate'], 'Date');
      if (data.hasOwnProperty('terms'))
        obj.terms = ApiClient.convertToType(data['terms'], 'String');
      if (data.hasOwnProperty('dueDate'))
        obj.dueDate = ApiClient.convertToType(data['dueDate'], 'Date');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [InvoiceItems]);
      if (data.hasOwnProperty('taxRate'))
        obj.taxRate = ApiClient.convertToType(data['taxRate'], 'Number');
      if (data.hasOwnProperty('invoiceBalance'))
        obj.invoiceBalance = ApiClient.convertToType(data['invoiceBalance'], 'Number');
      if (data.hasOwnProperty('invoiceNetTotal'))
        obj.invoiceNetTotal = ApiClient.convertToType(data['invoiceNetTotal'], 'Number');
      if (data.hasOwnProperty('dateEntered'))
        obj.dateEntered = ApiClient.convertToType(data['dateEntered'], 'Date');
      if (data.hasOwnProperty('dateModified'))
        obj.dateModified = ApiClient.convertToType(data['dateModified'], 'Date');
      if (data.hasOwnProperty('datePaid'))
        obj.datePaid = ApiClient.convertToType(data['datePaid'], 'Date');
      if (data.hasOwnProperty('paymentType'))
        obj.paymentType = ApiClient.convertToType(data['paymentType'], 'Date');
      if (data.hasOwnProperty('reference'))
        obj.reference = ApiClient.convertToType(data['reference'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Invoice.prototype.id = undefined;

/**
 * @member {module:model/ComponentsparametersvendorID} vendorID
 */
Invoice.prototype.vendorID = undefined;

/**
 * @member {Date} recieveDate
 */
Invoice.prototype.recieveDate = undefined;

/**
 * @member {String} terms
 */
Invoice.prototype.terms = undefined;

/**
 * @member {Date} dueDate
 */
Invoice.prototype.dueDate = undefined;

/**
 * @member {Array.<module:model/InvoiceItems>} items
 */
Invoice.prototype.items = undefined;

/**
 * @member {Number} taxRate
 */
Invoice.prototype.taxRate = undefined;

/**
 * @member {Number} invoiceBalance
 */
Invoice.prototype.invoiceBalance = undefined;

/**
 * @member {Number} invoiceNetTotal
 */
Invoice.prototype.invoiceNetTotal = undefined;

/**
 * @member {Date} dateEntered
 */
Invoice.prototype.dateEntered = undefined;

/**
 * @member {Date} dateModified
 */
Invoice.prototype.dateModified = undefined;

/**
 * @member {Date} datePaid
 */
Invoice.prototype.datePaid = undefined;

/**
 * @member {Date} paymentType
 */
Invoice.prototype.paymentType = undefined;

/**
 * @member {String} reference
 */
Invoice.prototype.reference = undefined;

