/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OrderOrdersItems} from './OrderOrdersItems';

/**
 * The Order model module.
 * @module model/Order
 * @version 1.5
 */
export class Order {
  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Order();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('userID'))
        obj.userID = ApiClient.convertToType(data['userID'], 'String');
      if (data.hasOwnProperty('ordersItems'))
        obj.ordersItems = ApiClient.convertToType(data['ordersItems'], [OrderOrdersItems]);
      if (data.hasOwnProperty('totalItems'))
        obj.totalItems = ApiClient.convertToType(data['totalItems'], 'Number');
      if (data.hasOwnProperty('taxRate'))
        obj.taxRate = ApiClient.convertToType(data['taxRate'], 'Number');
      if (data.hasOwnProperty('subtotal'))
        obj.subtotal = ApiClient.convertToType(data['subtotal'], 'Number');
      if (data.hasOwnProperty('grandTotal'))
        obj.grandTotal = ApiClient.convertToType(data['grandTotal'], 'Number');
      if (data.hasOwnProperty('addedDate'))
        obj.addedDate = ApiClient.convertToType(data['addedDate'], 'Date');
      if (data.hasOwnProperty('modifiedDate'))
        obj.modifiedDate = ApiClient.convertToType(data['modifiedDate'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Order.prototype.id = undefined;

/**
 * @member {String} userID
 */
Order.prototype.userID = undefined;

/**
 * @member {Array.<module:model/OrderOrdersItems>} ordersItems
 */
Order.prototype.ordersItems = undefined;

/**
 * @member {Number} totalItems
 */
Order.prototype.totalItems = undefined;

/**
 * @member {Number} taxRate
 */
Order.prototype.taxRate = undefined;

/**
 * @member {Number} subtotal
 */
Order.prototype.subtotal = undefined;

/**
 * @member {Number} grandTotal
 */
Order.prototype.grandTotal = undefined;

/**
 * @member {Date} addedDate
 */
Order.prototype.addedDate = undefined;

/**
 * @member {Date} modifiedDate
 */
Order.prototype.modifiedDate = undefined;

