/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Product} from './Product';

/**
 * The OrderOrdersItems model module.
 * @module model/OrderOrdersItems
 * @version 1.5
 */
export class OrderOrdersItems {
  /**
   * Constructs a new <code>OrderOrdersItems</code>.
   * @alias module:model/OrderOrdersItems
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderOrdersItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderOrdersItems} obj Optional instance to populate.
   * @return {module:model/OrderOrdersItems} The populated <code>OrderOrdersItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderOrdersItems();
      if (data.hasOwnProperty('cartID'))
        obj.cartID = ApiClient.convertToType(data['cartID'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('lineTotal'))
        obj.lineTotal = ApiClient.convertToType(data['lineTotal'], 'Number');
      if (data.hasOwnProperty('allOf'))
        obj.allOf = Product.constructFromObject(data['allOf']);
    }
    return obj;
  }
}

/**
 * @member {Number} cartID
 */
OrderOrdersItems.prototype.cartID = undefined;

/**
 * @member {Number} quantity
 */
OrderOrdersItems.prototype.quantity = undefined;

/**
 * @member {Number} lineTotal
 */
OrderOrdersItems.prototype.lineTotal = undefined;

/**
 * @member {module:model/Product} allOf
 */
OrderOrdersItems.prototype.allOf = undefined;

