/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Product model module.
 * @module model/Product
 * @version 1.5
 */
export class Product {
  /**
   * Constructs a new <code>Product</code>.
   * @alias module:model/Product
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('productName'))
        obj.productName = ApiClient.convertToType(data['productName'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('inventoryQuantity'))
        obj.inventoryQuantity = ApiClient.convertToType(data['inventoryQuantity'], 'Number');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('isFeatured'))
        obj.isFeatured = ApiClient.convertToType(data['isFeatured'], 'Boolean');
      if (data.hasOwnProperty('vendorId'))
        obj.vendorId = ApiClient.convertToType(data['vendorId'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], ['Blob']);
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
      if (data.hasOwnProperty('createdOn'))
        obj.createdOn = ApiClient.convertToType(data['createdOn'], 'Date');
      if (data.hasOwnProperty('updatedOn'))
        obj.updatedOn = ApiClient.convertToType(data['updatedOn'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Product.prototype.id = undefined;

/**
 * @member {String} productName
 */
Product.prototype.productName = undefined;

/**
 * @member {Number} price
 */
Product.prototype.price = undefined;

/**
 * @member {String} description
 */
Product.prototype.description = undefined;

/**
 * @member {Number} inventoryQuantity
 */
Product.prototype.inventoryQuantity = undefined;

/**
 * @member {String} category
 */
Product.prototype.category = undefined;

/**
 * @member {Boolean} isFeatured
 */
Product.prototype.isFeatured = undefined;

/**
 * @member {String} vendorId
 */
Product.prototype.vendorId = undefined;

/**
 * @member {Array.<Blob>} image
 */
Product.prototype.image = undefined;

/**
 * @member {String} unit
 */
Product.prototype.unit = undefined;

/**
 * @member {Date} createdOn
 */
Product.prototype.createdOn = undefined;

/**
 * @member {Date} updatedOn
 */
Product.prototype.updatedOn = undefined;

