/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address} from './Address';

/**
 * The Vendor model module.
 * @module model/Vendor
 * @version 1.5
 */
export class Vendor {
  /**
   * Constructs a new <code>Vendor</code>.
   * @alias module:model/Vendor
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Vendor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Vendor} obj Optional instance to populate.
   * @return {module:model/Vendor} The populated <code>Vendor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Vendor();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('vendorName'))
        obj.vendorName = ApiClient.convertToType(data['vendorName'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = Address.constructFromObject(data['address']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Vendor.prototype.id = undefined;

/**
 * @member {String} vendorName
 */
Vendor.prototype.vendorName = undefined;

/**
 * @member {String} email
 */
Vendor.prototype.email = undefined;

/**
 * @member {String} phoneNumber
 */
Vendor.prototype.phoneNumber = undefined;

/**
 * @member {module:model/Address} address
 */
Vendor.prototype.address = undefined;

