/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfBentleyEcommerceApi);
  }
}(this, function(expect, ProfBentleyEcommerceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CartCartItems', function() {
      beforeEach(function() {
        instance = new ProfBentleyEcommerceApi.CartCartItems();
      });

      it('should create an instance of CartCartItems', function() {
        // TODO: update the code to test CartCartItems
        expect(instance).to.be.a(ProfBentleyEcommerceApi.CartCartItems);
      });

      it('should have the property allOf (base name: "allOf")', function() {
        // TODO: update the code to test the property allOf
        expect(instance).to.have.property('allOf');
        // expect(instance.allOf).to.be(expectedValueLiteral);
      });

      it('should have the property cartID (base name: "cartID")', function() {
        // TODO: update the code to test the property cartID
        expect(instance).to.have.property('cartID');
        // expect(instance.cartID).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property lineTotal (base name: "lineTotal")', function() {
        // TODO: update the code to test the property lineTotal
        expect(instance).to.have.property('lineTotal');
        // expect(instance.lineTotal).to.be(expectedValueLiteral);
      });

    });
  });

}));
