/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfBentleyEcommerceApi);
  }
}(this, function(expect, ProfBentleyEcommerceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ExtendedErrorModel', function() {
      beforeEach(function() {
        instance = new ProfBentleyEcommerceApi.ExtendedErrorModel();
      });

      it('should create an instance of ExtendedErrorModel', function() {
        // TODO: update the code to test ExtendedErrorModel
        expect(instance).to.be.a(ProfBentleyEcommerceApi.ExtendedErrorModel);
      });

      it('should have the property rootCause (base name: "rootCause")', function() {
        // TODO: update the code to test the property rootCause
        expect(instance).to.have.property('rootCause');
        // expect(instance.rootCause).to.be(expectedValueLiteral);
      });

    });
  });

}));
