/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfbJsClient);
  }
}(this, function(expect, ProfbJsClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Method', function() {
      beforeEach(function() {
        instance = new ProfbJsClient.Method();
      });

      it('should create an instance of Method', function() {
        // TODO: update the code to test Method
        expect(instance).to.be.a(ProfbJsClient.Method);
      });

      it('should have the property mid (base name: "mid")', function() {
        // TODO: update the code to test the property mid
        expect(instance).to.have.property('mid');
        // expect(instance.mid).to.be(expectedValueLiteral);
      });

      it('should have the property method (base name: "method")', function() {
        // TODO: update the code to test the property method
        expect(instance).to.have.property('method');
        // expect(instance.method).to.be(expectedValueLiteral);
      });

      it('should have the property vid (base name: "vid")', function() {
        // TODO: update the code to test the property vid
        expect(instance).to.have.property('vid');
        // expect(instance.vid).to.be(expectedValueLiteral);
      });

      it('should have the property deliveryInHours (base name: "deliveryInHours")', function() {
        // TODO: update the code to test the property deliveryInHours
        expect(instance).to.have.property('deliveryInHours');
        // expect(instance.deliveryInHours).to.be(expectedValueLiteral);
      });

      it('should have the property price (base name: "price")', function() {
        // TODO: update the code to test the property price
        expect(instance).to.have.property('price');
        // expect(instance.price).to.be(expectedValueLiteral);
      });

    });
  });

}));
