/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfbJsClient);
  }
}(this, function(expect, ProfbJsClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Status', function() {
      beforeEach(function() {
        instance = new ProfbJsClient.Status();
      });

      it('should create an instance of Status', function() {
        // TODO: update the code to test Status
        expect(instance).to.be.a(ProfbJsClient.Status);
      });

      it('should have the property statusid (base name: "statusid")', function() {
        // TODO: update the code to test the property statusid
        expect(instance).to.have.property('statusid');
        // expect(instance.statusid).to.be(expectedValueLiteral);
      });

      it('should have the property statusName (base name: "statusName")', function() {
        // TODO: update the code to test the property statusName
        expect(instance).to.have.property('statusName');
        // expect(instance.statusName).to.be(expectedValueLiteral);
      });

      it('should have the property statusDescription (base name: "statusDescription")', function() {
        // TODO: update the code to test the property statusDescription
        expect(instance).to.have.property('statusDescription');
        // expect(instance.statusDescription).to.be(expectedValueLiteral);
      });

    });
  });

}));
