/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfbJsClient);
  }
}(this, function(expect, ProfbJsClient) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Type', function() {
      beforeEach(function() {
        instance = new ProfbJsClient.Type();
      });

      it('should create an instance of Type', function() {
        // TODO: update the code to test Type
        expect(instance).to.be.a(ProfbJsClient.Type);
      });

      it('should have the property typeid (base name: "typeid")', function() {
        // TODO: update the code to test the property typeid
        expect(instance).to.have.property('typeid');
        // expect(instance.typeid).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property typeDescription (base name: "typeDescription")', function() {
        // TODO: update the code to test the property typeDescription
        expect(instance).to.have.property('typeDescription');
        // expect(instance.typeDescription).to.be(expectedValueLiteral);
      });

    });
  });

}));
