/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Address model module.
* @module profb_client/apiModels/Address
* @version 1.67
*/
export default class Address {
    /**
    * Constructs a new <code>Address</code>.
    * An address object used in multiple types of records
    * @alias module:profb_client/apiModels/Address
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Address</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:profb_client/apiModels/Address} obj Optional instance to populate.
    * @return {module:profb_client/apiModels/Address} The populated <code>Address</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Address();
                        
            
            if (data.hasOwnProperty('addressid')) {
                obj['addressid'] = ApiClient.convertToType(data['addressid'], 'String');
            }
            if (data.hasOwnProperty('lineOne')) {
                obj['lineOne'] = ApiClient.convertToType(data['lineOne'], 'String');
            }
            if (data.hasOwnProperty('lineTwo')) {
                obj['lineTwo'] = ApiClient.convertToType(data['lineTwo'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('zipCode')) {
                obj['zipCode'] = ApiClient.convertToType(data['zipCode'], 'Number');
            }
            if (data.hasOwnProperty('typeid')) {
                obj['typeid'] = ApiClient.convertToType(data['typeid'], 'Number');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('updatedOn')) {
                obj['updatedOn'] = ApiClient.convertToType(data['updatedOn'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} addressid
    */
    'addressid' = undefined;
    /**
    * @member {String} lineOne
    */
    'lineOne' = undefined;
    /**
    * @member {String} lineTwo
    */
    'lineTwo' = undefined;
    /**
    * @member {String} city
    */
    'city' = undefined;
    /**
    * @member {String} state
    */
    'state' = undefined;
    /**
    * @member {Number} zipCode
    */
    'zipCode' = undefined;
    /**
    * @member {Number} typeid
    */
    'typeid' = undefined;
    /**
    * @member {Date} createdOn
    */
    'createdOn' = undefined;
    /**
    * @member {Date} updatedOn
    */
    'updatedOn' = undefined;




}
