/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Cart model module.
* @module profb_client/apiModels/Cart
* @version 1.67
*/
export default class Cart {
    /**
    * Constructs a new <code>Cart</code>.
    * user cart info
    * @alias module:profb_client/apiModels/Cart
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Cart</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:profb_client/apiModels/Cart} obj Optional instance to populate.
    * @return {module:profb_client/apiModels/Cart} The populated <code>Cart</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cart();
                        
            
            if (data.hasOwnProperty('cid')) {
                obj['cid'] = ApiClient.convertToType(data['cid'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('totalItems')) {
                obj['totalItems'] = ApiClient.convertToType(data['totalItems'], 'Number');
            }
            if (data.hasOwnProperty('isOrder')) {
                obj['isOrder'] = ApiClient.convertToType(data['isOrder'], 'Boolean');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('updatedOn')) {
                obj['updatedOn'] = ApiClient.convertToType(data['updatedOn'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} cid
    */
    'cid' = undefined;
    /**
    * @member {String} uid
    */
    'uid' = undefined;
    /**
    * @member {Number} total
    */
    'total' = undefined;
    /**
    * @member {Number} totalItems
    */
    'totalItems' = undefined;
    /**
    * @member {Boolean} isOrder
    */
    'isOrder' = undefined;
    /**
    * @member {Date} createdOn
    */
    'createdOn' = undefined;
    /**
    * @member {Date} updatedOn
    */
    'updatedOn' = undefined;




}
