/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Delivery model module.
* @module profb_client/apiModels/Delivery
* @version 1.67
*/
export default class Delivery {
    /**
    * Constructs a new <code>Delivery</code>.
    * the record of user order delivery
    * @alias module:profb_client/apiModels/Delivery
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Delivery</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:profb_client/apiModels/Delivery} obj Optional instance to populate.
    * @return {module:profb_client/apiModels/Delivery} The populated <code>Delivery</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Delivery();
                        
            
            if (data.hasOwnProperty('deliveryId')) {
                obj['deliveryId'] = ApiClient.convertToType(data['deliveryId'], 'String');
            }
            if (data.hasOwnProperty('estDelivery')) {
                obj['estDelivery'] = ApiClient.convertToType(data['estDelivery'], 'Date');
            }
            if (data.hasOwnProperty('deliveryTotal')) {
                obj['deliveryTotal'] = ApiClient.convertToType(data['deliveryTotal'], 'Number');
            }
            if (data.hasOwnProperty('oid')) {
                obj['oid'] = ApiClient.convertToType(data['oid'], 'String');
            }
            if (data.hasOwnProperty('mid')) {
                obj['mid'] = ApiClient.convertToType(data['mid'], 'Number');
            }
            if (data.hasOwnProperty('statusid')) {
                obj['statusid'] = ApiClient.convertToType(data['statusid'], 'Number');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('updatedOn')) {
                obj['updatedOn'] = ApiClient.convertToType(data['updatedOn'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {String} deliveryId
    */
    'deliveryId' = undefined;
    /**
    * @member {Date} estDelivery
    */
    'estDelivery' = undefined;
    /**
    * @member {Number} deliveryTotal
    */
    'deliveryTotal' = undefined;
    /**
    * @member {String} oid
    */
    'oid' = undefined;
    /**
    * @member {Number} mid
    */
    'mid' = undefined;
    /**
    * @member {Number} statusid
    */
    'statusid' = undefined;
    /**
    * @member {Date} createdOn
    */
    'createdOn' = undefined;
    /**
    * @member {Date} updatedOn
    */
    'updatedOn' = undefined;




}
