/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ErrorModel from './ErrorModel';

/**
* The ExtendedErrorModel model module.
* @module profb_client/apiModels/ExtendedErrorModel
* @version 1.67
*/
export default class ExtendedErrorModel {
    /**
    * Constructs a new <code>ExtendedErrorModel</code>.
    * @alias module:profb_client/apiModels/ExtendedErrorModel
    * @class
    * @extends module:profb_client/apiModels/ErrorModel
    * @param message {} 
    * @param code {} 
    * @param rootCause {} 
    */

    constructor(message, code, rootCause) {
        ErrorModel.call(this, message, code);
        
        this['rootCause'] = rootCause;
        
    }

    /**
    * Constructs a <code>ExtendedErrorModel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:profb_client/apiModels/ExtendedErrorModel} obj Optional instance to populate.
    * @return {module:profb_client/apiModels/ExtendedErrorModel} The populated <code>ExtendedErrorModel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExtendedErrorModel();
            
            ErrorModel.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('rootCause')) {
                obj['rootCause'] = ApiClient.convertToType(data['rootCause'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} rootCause
    */
    'rootCause' = undefined;




}
