/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExtendedErrorModel from './ExtendedErrorModel';

/**
* The InlineResponse404 model module.
* @module profb_client/apiModels/InlineResponse404
* @version 1.67
*/
export default class InlineResponse404 {
    /**
    * Constructs a new <code>InlineResponse404</code>.
    * @alias module:profb_client/apiModels/InlineResponse404
    * @class
    * @extends module:profb_client/apiModels/ExtendedErrorModel
    * @param rootCause {} 
    */

    constructor(rootCause) {
        ExtendedErrorModel.call(this, message, code, rootCause);
        
        
    }

    /**
    * Constructs a <code>InlineResponse404</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:profb_client/apiModels/InlineResponse404} obj Optional instance to populate.
    * @return {module:profb_client/apiModels/InlineResponse404} The populated <code>InlineResponse404</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse404();
            
            ExtendedErrorModel.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} message
    * @default 'Error! Requested Information Not FOund'
    */
    'message' = 'Error! Requested Information Not FOund';
    /**
    * @member {Number} code
    * @default 404
    */
    'code' = 404;




}
