/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Status model module.
* @module profb_client/apiModels/Status
* @version 1.67
*/
export default class Status {
    /**
    * Constructs a new <code>Status</code>.
    * a table of different status used in multiple types of records
    * @alias module:profb_client/apiModels/Status
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Status</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:profb_client/apiModels/Status} obj Optional instance to populate.
    * @return {module:profb_client/apiModels/Status} The populated <code>Status</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Status();
                        
            
            if (data.hasOwnProperty('statusid')) {
                obj['statusid'] = ApiClient.convertToType(data['statusid'], 'Number');
            }
            if (data.hasOwnProperty('statusName')) {
                obj['statusName'] = ApiClient.convertToType(data['statusName'], 'String');
            }
            if (data.hasOwnProperty('statusDescription')) {
                obj['statusDescription'] = ApiClient.convertToType(data['statusDescription'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} statusid
    */
    'statusid' = undefined;
    /**
    * @member {String} statusName
    */
    'statusName' = undefined;
    /**
    * @member {String} statusDescription
    */
    'statusDescription' = undefined;




}
