/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Orderid} from '../Orderid';
import {Payment} from '../Payment';

/**
* Checkout service.
* @module CheckoutApi
* @version 1.67
*/
export class CheckoutApi {

    /**
    * Constructs a new CheckoutApi. 
    * @alias module:CheckoutApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the postPayment operation.
     * @callback moduleCheckoutApi~postPaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:Payment{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * post a payment for user order
     * endpoint to checkout a user order
     * @param {module:Orderid} orderid 
     * @param {Object} opts Optional parameters
     * @param {module:Payment} opts.body a new user payment object
     * @param {module:CheckoutApi~postPaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    postPayment(orderid, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'orderid' is set
      if (orderid === undefined || orderid === null) {
        throw new Error("Missing the required parameter 'orderid' when calling postPayment");
      }

      let pathParams = {
        'orderid': orderid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basic'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded'];
      let accepts = ['application/json'];
      let returnType = Payment;

      return this.apiClient.callApi(
        '/checkout/{orderid}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}