/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Product} from '../Product';
import {Productid} from '../Productid';
import {User} from '../User';

/**
* Products service.
* @module ProductsApi
* @version 1.67
*/
export class ProductsApi {

    /**
    * Constructs a new ProductsApi. 
    * @alias module:ProductsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getAllproducts operation.
     * @callback moduleProductsApi~getAllproductsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:Product>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * fetchs all product records
     * endpoint to get an array of all product records
     * @param {module:ProductsApi~getAllproductsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getAllproducts(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Product];

      return this.apiClient.callApi(
        '/store/products', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getProduct operation.
     * @callback moduleProductsApi~getProductCallback
     * @param {String} error Error message, if any.
     * @param {module:Product{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get user record by id
     * endpoint to get a single user record
     * @param {module:Productid} productid 
     * @param {module:ProductsApi~getProductCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getProduct(productid, callback) {
      
      let postBody = null;
      // verify the required parameter 'productid' is set
      if (productid === undefined || productid === null) {
        throw new Error("Missing the required parameter 'productid' when calling getProduct");
      }

      let pathParams = {
        'productid': productid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basic'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Product;

      return this.apiClient.callApi(
        '/store/products/{productid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateProduct operation.
     * @callback moduleProductsApi~updateProductCallback
     * @param {String} error Error message, if any.
     * @param {module:User{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update user record by id
     * endpoint to update a single user record
     * @param {module:Productid} productid 
     * @param {Object} opts Optional parameters
     * @param {module:Product} opts.body A new product to add to the system
     * @param {module:ProductsApi~updateProductCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateProduct(productid, opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];
      // verify the required parameter 'productid' is set
      if (productid === undefined || productid === null) {
        throw new Error("Missing the required parameter 'productid' when calling updateProduct");
      }

      let pathParams = {
        'productid': productid
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basic'];
      let contentTypes = ['application/json', 'application/x-urlencoded'];
      let accepts = ['application/json'];
      let returnType = User;

      return this.apiClient.callApi(
        '/store/products/{productid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}