/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Product model module.
 * @module Product
 * @version 1.67
 */
export class Product {
  /**
   * Constructs a new <code>Product</code>.
   * Product record with product info
   * @alias module:Product
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Product} obj Optional instance to populate.
   * @return {module:Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('pid'))
        obj.pid = ApiClient.convertToType(data['pid'], 'String');
      if (data.hasOwnProperty('productName'))
        obj.productName = ApiClient.convertToType(data['productName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('onHandQuantity'))
        obj.onHandQuantity = ApiClient.convertToType(data['onHandQuantity'], 'Number');
      if (data.hasOwnProperty('isFeature'))
        obj.isFeature = ApiClient.convertToType(data['isFeature'], 'Boolean');
      if (data.hasOwnProperty('catId'))
        obj.catId = ApiClient.convertToType(data['catId'], 'Number');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'Blob');
      if (data.hasOwnProperty('vid'))
        obj.vid = ApiClient.convertToType(data['vid'], 'String');
      if (data.hasOwnProperty('createdOn'))
        obj.createdOn = ApiClient.convertToType(data['createdOn'], 'Date');
      if (data.hasOwnProperty('updatedOn'))
        obj.updatedOn = ApiClient.convertToType(data['updatedOn'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} pid
 */
Product.prototype.pid = undefined;

/**
 * @member {String} productName
 */
Product.prototype.productName = undefined;

/**
 * @member {String} description
 */
Product.prototype.description = undefined;

/**
 * @member {Number} price
 */
Product.prototype.price = undefined;

/**
 * @member {Number} onHandQuantity
 */
Product.prototype.onHandQuantity = undefined;

/**
 * @member {Boolean} isFeature
 */
Product.prototype.isFeature = undefined;

/**
 * @member {Number} catId
 */
Product.prototype.catId = undefined;

/**
 * @member {Blob} image
 */
Product.prototype.image = undefined;

/**
 * @member {String} vid
 */
Product.prototype.vid = undefined;

/**
 * @member {Date} createdOn
 */
Product.prototype.createdOn = undefined;

/**
 * @member {Date} updatedOn
 */
Product.prototype.updatedOn = undefined;

