/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Userid model module.
 * @module Userid
 * @version 1.67
 */
export class Userid {
  /**
   * Constructs a new <code>Userid</code>.
   * @alias module:Userid
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Userid</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:Userid} obj Optional instance to populate.
   * @return {module:Userid} The populated <code>Userid</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Userid();
    }
    return obj;
  }
}
