/*
 * Prof Bentley Ecommerce API
 * A Ecommerce API
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfBentleyEcommerceApi);
  }
}(this, function(expect, ProfBentleyEcommerceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProfBentleyEcommerceApi.ProductsApi();
  });

  describe('(package)', function() {
    describe('ProductsApi', function() {
      describe('deleteProduct', function() {
        it('should call deleteProduct successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteProduct call
          /*

          instance.deleteProduct(productID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('filterProducts', function() {
        it('should call filterProducts successfully', function(done) {
          // TODO: uncomment filterProducts call
          /*

          instance.filterProducts(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getAllProducts', function() {
        it('should call getAllProducts successfully', function(done) {
          // TODO: uncomment getAllProducts call and complete the assertions
          /*

          instance.getAllProducts(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(ProfBentleyEcommerceApi.Cart);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getProduct', function() {
        it('should call getProduct successfully', function(done) {
          // TODO: uncomment, update parameter values for getProduct call and complete the assertions
          /*

          instance.getProduct(productID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfBentleyEcommerceApi.Product);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postProduct', function() {
        it('should call postProduct successfully', function(done) {
          // TODO: uncomment, update parameter values for postProduct call and complete the assertions
          /*
          var opts = {};

          instance.postProduct(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfBentleyEcommerceApi.Product);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('searchStore', function() {
        it('should call searchStore successfully', function(done) {
          // TODO: uncomment, update parameter values for searchStore call
          /*

          instance.searchStore(searchterm, category, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateProduct', function() {
        it('should call updateProduct successfully', function(done) {
          // TODO: uncomment, update parameter values for updateProduct call and complete the assertions
          /*

          instance.updateProduct(productID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(ProfBentleyEcommerceApi.Product);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
