/**
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.5
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Address from './apiModels/Address';
import Cart from './apiModels/Cart';
import CartItems from './apiModels/CartItems';
import Category from './apiModels/Category';
import Delivery from './apiModels/Delivery';
import ErrorModel from './apiModels/ErrorModel';
import ExtendedErrorModel from './apiModels/ExtendedErrorModel';
import InlineResponse200 from './apiModels/InlineResponse200';
import InlineResponse404 from './apiModels/InlineResponse404';
import Method from './apiModels/Method';
import Order from './apiModels/Order';
import OrderItems from './apiModels/OrderItems';
import Payment from './apiModels/Payment';
import Product from './apiModels/Product';
import Status from './apiModels/Status';
import Type from './apiModels/Type';
import User from './apiModels/User';
import UserAddress from './apiModels/UserAddress';
import Vendor from './apiModels/Vendor';
import AuthApi from './api_classes/AuthApi';
import CartApi from './api_classes/CartApi';
import CheckoutApi from './api_classes/CheckoutApi';
import OrdersApi from './api_classes/OrdersApi';
import ProductsApi from './api_classes/ProductsApi';
import StoreApi from './api_classes/StoreApi';
import UsersApi from './api_classes/UsersApi';
import VendorsApi from './api_classes/VendorsApi';

/**
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var profbent = require('profb_client/index'); // See note below*.
* var xxxSvc = new profbent.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new profbent.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['profb_client/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new profbent.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new profbent.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module profb_client/index
* @version 1.67
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:profb_client/ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:profb_client/apiModels/Address}
     */
    Address,

    /**
     * The Cart model constructor.
     * @property {module:profb_client/apiModels/Cart}
     */
    Cart,

    /**
     * The CartItems model constructor.
     * @property {module:profb_client/apiModels/CartItems}
     */
    CartItems,

    /**
     * The Category model constructor.
     * @property {module:profb_client/apiModels/Category}
     */
    Category,

    /**
     * The Delivery model constructor.
     * @property {module:profb_client/apiModels/Delivery}
     */
    Delivery,

    /**
     * The ErrorModel model constructor.
     * @property {module:profb_client/apiModels/ErrorModel}
     */
    ErrorModel,

    /**
     * The ExtendedErrorModel model constructor.
     * @property {module:profb_client/apiModels/ExtendedErrorModel}
     */
    ExtendedErrorModel,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:profb_client/apiModels/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse404 model constructor.
     * @property {module:profb_client/apiModels/InlineResponse404}
     */
    InlineResponse404,

    /**
     * The Method model constructor.
     * @property {module:profb_client/apiModels/Method}
     */
    Method,

    /**
     * The Order model constructor.
     * @property {module:profb_client/apiModels/Order}
     */
    Order,

    /**
     * The OrderItems model constructor.
     * @property {module:profb_client/apiModels/OrderItems}
     */
    OrderItems,

    /**
     * The Payment model constructor.
     * @property {module:profb_client/apiModels/Payment}
     */
    Payment,

    /**
     * The Product model constructor.
     * @property {module:profb_client/apiModels/Product}
     */
    Product,

    /**
     * The Status model constructor.
     * @property {module:profb_client/apiModels/Status}
     */
    Status,

    /**
     * The Type model constructor.
     * @property {module:profb_client/apiModels/Type}
     */
    Type,

    /**
     * The User model constructor.
     * @property {module:profb_client/apiModels/User}
     */
    User,

    /**
     * The UserAddress model constructor.
     * @property {module:profb_client/apiModels/UserAddress}
     */
    UserAddress,

    /**
     * The Vendor model constructor.
     * @property {module:profb_client/apiModels/Vendor}
     */
    Vendor,

    /**
    * The AuthApi service constructor.
    * @property {module:profb_client/api_classes/AuthApi}
    */
    AuthApi,

    /**
    * The CartApi service constructor.
    * @property {module:profb_client/api_classes/CartApi}
    */
    CartApi,

    /**
    * The CheckoutApi service constructor.
    * @property {module:profb_client/api_classes/CheckoutApi}
    */
    CheckoutApi,

    /**
    * The OrdersApi service constructor.
    * @property {module:profb_client/api_classes/OrdersApi}
    */
    OrdersApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:profb_client/api_classes/ProductsApi}
    */
    ProductsApi,

    /**
    * The StoreApi service constructor.
    * @property {module:profb_client/api_classes/StoreApi}
    */
    StoreApi,

    /**
    * The UsersApi service constructor.
    * @property {module:profb_client/api_classes/UsersApi}
    */
    UsersApi,

    /**
    * The VendorsApi service constructor.
    * @property {module:profb_client/api_classes/VendorsApi}
    */
    VendorsApi
};
