/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.1
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfessorBentleyElectronicsRetailApi);
  }
}(this, function(expect, ProfessorBentleyElectronicsRetailApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Delivery', function() {
      beforeEach(function() {
        instance = new ProfessorBentleyElectronicsRetailApi.Delivery();
      });

      it('should create an instance of Delivery', function() {
        // TODO: update the code to test Delivery
        expect(instance).to.be.a(ProfessorBentleyElectronicsRetailApi.Delivery);
      });

      it('should have the property deliveryId (base name: "deliveryId")', function() {
        // TODO: update the code to test the property deliveryId
        expect(instance).to.have.property('deliveryId');
        // expect(instance.deliveryId).to.be(expectedValueLiteral);
      });

      it('should have the property estDelivery (base name: "estDelivery")', function() {
        // TODO: update the code to test the property estDelivery
        expect(instance).to.have.property('estDelivery');
        // expect(instance.estDelivery).to.be(expectedValueLiteral);
      });

      it('should have the property deliveryTotal (base name: "deliveryTotal")', function() {
        // TODO: update the code to test the property deliveryTotal
        expect(instance).to.have.property('deliveryTotal');
        // expect(instance.deliveryTotal).to.be(expectedValueLiteral);
      });

      it('should have the property oid (base name: "oid")', function() {
        // TODO: update the code to test the property oid
        expect(instance).to.have.property('oid');
        // expect(instance.oid).to.be(expectedValueLiteral);
      });

      it('should have the property mid (base name: "mid")', function() {
        // TODO: update the code to test the property mid
        expect(instance).to.have.property('mid');
        // expect(instance.mid).to.be(expectedValueLiteral);
      });

      it('should have the property statusid (base name: "statusid")', function() {
        // TODO: update the code to test the property statusid
        expect(instance).to.have.property('statusid');
        // expect(instance.statusid).to.be(expectedValueLiteral);
      });

      it('should have the property createdOn (base name: "createdOn")', function() {
        // TODO: update the code to test the property createdOn
        expect(instance).to.have.property('createdOn');
        // expect(instance.createdOn).to.be(expectedValueLiteral);
      });

      it('should have the property updatedOn (base name: "updatedOn")', function() {
        // TODO: update the code to test the property updatedOn
        expect(instance).to.have.property('updatedOn');
        // expect(instance.updatedOn).to.be(expectedValueLiteral);
      });

    });
  });

}));
