/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.1
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfessorBentleyElectronicsRetailApi);
  }
}(this, function(expect, ProfessorBentleyElectronicsRetailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProfessorBentleyElectronicsRetailApi.CartApi();
  });

  describe('(package)', function() {
    describe('CartApi', function() {
      describe('addCartItems', function() {
        it('should call addCartItems successfully', function(done) {
          // TODO: uncomment, update parameter values for addCartItems call and complete the assertions
          /*

          instance.addCartItems(cartid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfessorBentleyElectronicsRetailApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postNewCart', function() {
        it('should call postNewCart successfully', function(done) {
          // TODO: uncomment postNewCart call and complete the assertions
          /*

          instance.postNewCart(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfessorBentleyElectronicsRetailApi.Cart);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateCartItems', function() {
        it('should call updateCartItems successfully', function(done) {
          // TODO: uncomment, update parameter values for updateCartItems call and complete the assertions
          /*

          instance.updateCartItems(cartid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfessorBentleyElectronicsRetailApi.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
