/*
 * Professor Bentley Electronics Retail API
 * An ecommerce REST API for a retail electronics store. 
 *
 * OpenAPI spec version: 1.1
 * Contact: jordanh316@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProfessorBentleyElectronicsRetailApi);
  }
}(this, function(expect, ProfessorBentleyElectronicsRetailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProfessorBentleyElectronicsRetailApi.VendorsApi();
  });

  describe('(package)', function() {
    describe('VendorsApi', function() {
      describe('getAllvendors', function() {
        it('should call getAllvendors successfully', function(done) {
          // TODO: uncomment getAllvendors call and complete the assertions
          /*

          instance.getAllvendors(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(ProfessorBentleyElectronicsRetailApi.Vendor);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getVendor', function() {
        it('should call getVendor successfully', function(done) {
          // TODO: uncomment, update parameter values for getVendor call and complete the assertions
          /*

          instance.getVendor(vendorid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfessorBentleyElectronicsRetailApi.Vendor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateVendor', function() {
        it('should call updateVendor successfully', function(done) {
          // TODO: uncomment, update parameter values for updateVendor call and complete the assertions
          /*
          var opts = {};

          instance.updateVendor(vendorid, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ProfessorBentleyElectronicsRetailApi.Vendor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
